services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres:18
    container_name: air_ops_postgres
    labels:
      - "org.springframework.boot.ignore=true"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-air_ops}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
